server:
  port: 8888

spring:
  data:
    redis:
      port: 6379
      host: 127.0.0.1
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: -1ms

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3308/lostandfound?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: text
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 20
      min-idle: 10
      max-active: 100
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.zjitc.lostandfound_api.pojo
  mapper-locations: classpath:mapper/*.xml

minio:
  endPoint: http://www.ppg6.store:9000
  accessKey: PPG
  secretKey: 123@XyjPPG
  bucketName: public